$ErrorActionPreference = 'Stop'

function Get-UeefManagedRequirementsPath {
  param([string]$CodexHome = '')
  if ($IsWindows -or $env:OS -eq 'Windows_NT') {
    if ([string]::IsNullOrWhiteSpace($env:ProgramData)) { throw 'ProgramData is unavailable for managed Codex requirements.' }
    return (Join-Path $env:ProgramData 'OpenAI\Codex\requirements.toml')
  }
  return '/etc/codex/requirements.toml'
}

function Test-UeefOwnedRequirements([string]$Path) {
  if (!(Test-Path -LiteralPath $Path -PathType Leaf)) { return $false }
  return [IO.File]::ReadAllText($Path, [Text.Encoding]::UTF8).StartsWith('# UEEF-MANAGED-REQUIREMENTS', [StringComparison]::Ordinal)
}

function Get-UeefManagedRequirementsText([string]$HooksPath, [string]$NodePath) {
  if ($HooksPath.Contains("'") -or $NodePath.Contains("'")) { throw 'Managed hooks and Node paths cannot contain a single quote.' }
  $hook = Join-Path $HooksPath 'ueef-codex-hook.mjs'
  $command = "`"$NodePath`" `"$hook`""
  $lines = [Collections.Generic.List[string]]::new()
  @(
    '# UEEF-MANAGED-REQUIREMENTS',
    '# Generated by UEEF. Preserve by synchronizing the runtime; do not hand-edit.',
    '',
    '[features]',
    'hooks = true',
    '',
    '[hooks]'
  ) | ForEach-Object { $lines.Add($_) }
  if ($IsWindows -or $env:OS -eq 'Windows_NT') { $lines.Add("windows_managed_dir = '$HooksPath'") }
  else { $lines.Add("managed_dir = '$HooksPath'") }
  foreach ($eventName in @('SessionStart','UserPromptSubmit','PreToolUse','PostToolUse','Stop')) {
    $lines.Add('')
    $lines.Add("[[hooks.$eventName]]")
    $lines.Add('')
    $lines.Add("[[hooks.$eventName.hooks]]")
    $lines.Add("type = 'command'")
    $lines.Add("command = '$command'")
    $lines.Add("command_windows = '$command'")
    $lines.Add('timeout = 20')
    $lines.Add("statusMessage = 'Applying UEEF managed enforcement'")
    if ($eventName -in @('SessionStart','UserPromptSubmit')) { $lines.Add('additionalContextLimit = 3000') }
  }
  return ($lines -join [Environment]::NewLine) + [Environment]::NewLine
}

function Install-UeefManagedEnforcement {
  [CmdletBinding()]
  param(
    [Parameter(Mandatory)][string]$RuntimePath,
    [Parameter(Mandatory)][string]$RuntimeRoot,
    [Parameter(Mandatory)][string]$RequirementsPath,
    [string]$NodePath = ''
  )
  if ([string]::IsNullOrWhiteSpace($NodePath)) {
    $nodeCommand = Get-Command node -ErrorAction SilentlyContinue
    if (!$nodeCommand) { throw 'Node.js is required for low-latency managed Codex hooks.' }
    $NodePath = $nodeCommand.Source
  }
  $NodePath = [IO.Path]::GetFullPath($NodePath)
  if (!(Test-Path -LiteralPath $NodePath -PathType Leaf)) { throw "Node.js executable not found: $NodePath" }
  $resolvedRuntimePath = (Resolve-Path -LiteralPath $RuntimePath).Path
  $sourceHookRoot = Join-Path $resolvedRuntimePath 'scripts\codex-hooks'
  $policySource = Join-Path $resolvedRuntimePath 'config\codex-enforcement-policy.json'
  $modelPolicySource = Join-Path $resolvedRuntimePath 'config\model-routing-policy.json'
  $modelResolverSource = Join-Path $resolvedRuntimePath 'scripts\resolve-model-route.mjs'
  $modelDiscoverySource = Join-Path $resolvedRuntimePath 'scripts\codex-app-server-models.mjs'
  foreach ($required in @((Join-Path $sourceHookRoot 'ueef-codex-hook.mjs'),(Join-Path $sourceHookRoot 'record-ueef-route.mjs'),(Join-Path $sourceHookRoot 'ueef-hook-common.mjs'),$policySource,$modelPolicySource,$modelResolverSource,$modelDiscoverySource)) {
    if (!(Test-Path -LiteralPath $required -PathType Leaf)) { throw "Managed enforcement source missing: $required" }
  }
  if (Test-Path -LiteralPath $RequirementsPath) {
    $item = Get-Item -LiteralPath $RequirementsPath -Force
    if (($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { throw "Refusing reparse-point managed requirements: $RequirementsPath" }
    if (!(Test-UeefOwnedRequirements $RequirementsPath)) { throw "Managed requirements already exist and are not UEEF-owned: $RequirementsPath" }
  }
  New-Item -ItemType Directory -Path $RuntimeRoot -Force | Out-Null
  $runtimeRootItem = Get-Item -LiteralPath $RuntimeRoot -Force
  if (($runtimeRootItem.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { throw "Refusing reparse-point runtime root: $RuntimeRoot" }
  $hooksPath = Join-Path $RuntimeRoot 'managed-hooks'
  $staging = Join-Path $RuntimeRoot ('.hooks-' + [guid]::NewGuid().ToString('N'))
  $rollback = Join-Path $RuntimeRoot ('.hooks-rollback-' + [guid]::NewGuid().ToString('N'))
  $requirementsExisted = Test-Path -LiteralPath $RequirementsPath -PathType Leaf
  $requirementsBefore = if ($requirementsExisted) { [IO.File]::ReadAllText($RequirementsPath, [Text.Encoding]::UTF8) } else { $null }
  try {
    New-Item -ItemType Directory -Path $staging -Force | Out-Null
    foreach ($name in @('ueef-codex-hook.mjs','record-ueef-route.mjs','ueef-hook-common.mjs')) { Copy-Item -LiteralPath (Join-Path $sourceHookRoot $name) -Destination (Join-Path $staging $name) }
    Copy-Item -LiteralPath $policySource -Destination (Join-Path $staging 'codex-enforcement-policy.json')
    Copy-Item -LiteralPath $modelPolicySource -Destination (Join-Path $staging 'model-routing-policy.json')
    Copy-Item -LiteralPath $modelResolverSource -Destination (Join-Path $staging 'resolve-model-route.mjs')
    Copy-Item -LiteralPath $modelDiscoverySource -Destination (Join-Path $staging 'codex-app-server-models.mjs')
    if (Test-Path -LiteralPath $hooksPath) {
      $hooksItem = Get-Item -LiteralPath $hooksPath -Force
      if (($hooksItem.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { throw "Refusing reparse-point managed hooks: $hooksPath" }
      Move-Item -LiteralPath $hooksPath -Destination $rollback
    }
    Move-Item -LiteralPath $staging -Destination $hooksPath
    $requirementsText = Get-UeefManagedRequirementsText $hooksPath $NodePath
    New-Item -ItemType Directory -Path (Split-Path -Parent $RequirementsPath) -Force | Out-Null
    $requirementsTemporary = "$RequirementsPath.tmp.$([guid]::NewGuid().ToString('N'))"
    [IO.File]::WriteAllText($requirementsTemporary, $requirementsText, [Text.UTF8Encoding]::new($false))
    Move-Item -LiteralPath $requirementsTemporary -Destination $RequirementsPath -Force
    if (Test-Path -LiteralPath $rollback) { Remove-Item -LiteralPath $rollback -Recurse -Force }
  } catch {
    $failure = $_
    if (Test-Path -LiteralPath $hooksPath) { Remove-Item -LiteralPath $hooksPath -Recurse -Force }
    if (Test-Path -LiteralPath $rollback) { Move-Item -LiteralPath $rollback -Destination $hooksPath }
    if ($requirementsExisted) { [IO.File]::WriteAllText($RequirementsPath, $requirementsBefore, [Text.UTF8Encoding]::new($false)) }
    elseif (Test-Path -LiteralPath $RequirementsPath) { Remove-Item -LiteralPath $RequirementsPath -Force }
    if (Test-Path -LiteralPath $staging) { Remove-Item -LiteralPath $staging -Recurse -Force }
    throw $failure
  }
  $hookFiles = @('ueef-codex-hook.mjs','record-ueef-route.mjs','ueef-hook-common.mjs','codex-enforcement-policy.json','model-routing-policy.json','resolve-model-route.mjs','codex-app-server-models.mjs') | ForEach-Object {
    $path = Join-Path $hooksPath $_
    [pscustomobject]@{relativePath=$_;sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()}
  }
  return [pscustomobject]@{
    schemaVersion = 1
    requirementsPath = [IO.Path]::GetFullPath($RequirementsPath)
    requirementsSha256 = (Get-FileHash -LiteralPath $RequirementsPath -Algorithm SHA256).Hash.ToLowerInvariant()
    hooksPath = [IO.Path]::GetFullPath($hooksPath)
    nodePath = $NodePath
    hookFiles = $hookFiles
  }
}
