#!/usr/bin/env sh
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
v="$ROOT/scripts/validate-goal-lifecycle.sh"
audit=$(mktemp)
bad_audit=$(mktemp)
trap 'rm -f "$audit" "$bad_audit"' EXIT
printf '%s\n' '{"schemaVersion":2,"taskId":"unix-fixture","auditedAt":"2026-08-02T00:00:00Z","requestedOutcome":"Fixture outcome","sourceReview":{"coverageMode":"verbatim-segments","sourceText":"Fixture goal.","sourceSha256":"90006FF8D381D635B2639E17EBBF6B925FF91F680F475DCB81D2181FBE25E801","status":"PASS","reviewUnits":[{"id":"RU-1","classification":"requirement","sourceQuote":"Fixture goal.","start":0,"end":13,"status":"PASS","linkedRequirements":["REQ-1"]}]},"requirements":[{"id":"REQ-1","text":"Fixture requirement","status":"PASS","acceptanceCriteria":["AC-1"]}],"acceptanceCriteria":[{"id":"AC-1","text":"Fixture behavior verified","status":"PASS","evidence":[{"kind":"test","source":"fixture","result":"PASS","observedAt":"2026-08-02T00:00:00Z"}]}],"implementationReview":{"implementationCompletedAt":"2026-08-02T00:00:00Z","goalReviewStartedAt":"2026-08-02T00:00:00Z","transitionAnnounced":true,"goalRemainedActiveDuringReview":true,"requestedImplementationStatus":"PASS","bestFeasibleOutcomeStatus":"PASS","bestFeasibleOutcomeRationale":"Canonical implementation satisfies the request.","status":"PASS"},"completionChecklist":[{"requirementId":"REQ-1","sourceReviewUnits":["RU-1"],"acceptanceCriteria":["AC-1"],"requestedImplementationStatus":"PASS","bestFeasibleOutcomeStatus":"PASS","bestFeasibleOutcomeRationale":"Requirement is satisfied with current evidence.","checked":true,"status":"PASS"}],"regressionReview":{"scope":"Task changes only","changedSurfaces":["shell fixture"],"checks":[{"surface":"shell fixture","evidence":"focused shell test","result":"PASS"}],"taskCausedRegressions":[],"unrelatedFindings":[],"status":"PASS"},"remainingWork":[],"knownProblems":[],"conclusion":"COMPLETE"}' > "$audit"
node -e "const fs=require('fs');const p=process.argv[1];const a=JSON.parse(fs.readFileSync(p,'utf8'));a.userCommitmentReview={explicitBeforeFinishRequestDetected:false,clarificationAskedBeforeCompletion:false,resolutionEvidence:['No before-finish commitment in fixture.'],pendingCommitments:[],status:'PASS'};a.goalUpdateReview={updatesReceived:0,allReceivedUpdatesClassified:true,updateDetectionStatus:'PASS',routes:[],pendingUpdates:[],openResumePoints:[],status:'PASS'};a.implementationReview.goalToImplementationComparisonStatus='PASS';a.implementationReview.actualImplementationInventory=[{id:'IMP-1',surface:'shell fixture',observedBehavior:'Fixture behavior passes',evidence:'focused shell test',linkedRequirements:['REQ-1'],status:'PASS'}];a.implementationReview.missingImplementation=[];a.implementationReview.untracedImplementation=[];a.completionChecklist[0].actualImplementationIds=['IMP-1'];a.completionChecklist[0].goalToImplementationComparisonStatus='PASS';fs.writeFileSync(p,JSON.stringify(a));" "$audit"
cp "$audit" "$bad_audit"
node -e "const fs=require('fs');const p=process.argv[1];const a=JSON.parse(fs.readFileSync(p,'utf8'));a.acceptanceCriteria[0].evidence[0].observedAt='2026-08-02T00:05:00Z';fs.writeFileSync(p,JSON.stringify(a));" "$bad_audit"
if sh "$ROOT/scripts/validate-completion-audit.sh" "$bad_audit" >/dev/null 2>&1; then echo 'Portable completion audit accepted future evidence' >&2; exit 1; fi
cp "$audit" "$bad_audit"
node -e "const fs=require('fs');const p=process.argv[1];const a=JSON.parse(fs.readFileSync(p,'utf8'));a.acceptanceCriteria.push({...a.acceptanceCriteria[0]});fs.writeFileSync(p,JSON.stringify(a));" "$bad_audit"
if sh "$ROOT/scripts/validate-completion-audit.sh" "$bad_audit" >/dev/null 2>&1; then echo 'Portable completion audit accepted duplicate criterion id' >&2; exit 1; fi
if "$v" --goal-status ACTIVE --terminal-final >/dev/null 2>&1; then echo 'ACTIVE terminal final accepted' >&2; exit 1; fi
if "$v" --goal-status COMPLETE --terminal-final --required-work-remaining >/dev/null 2>&1; then echo 'Invalid COMPLETE accepted' >&2; exit 1; fi
if "$v" --goal-status BLOCKED --terminal-final >/dev/null 2>&1; then echo 'Invalid BLOCKED accepted' >&2; exit 1; fi
if "$v" --goal-status COMPLETE --terminal-final --outcome-satisfied --gates-pass-or-accepted --verification-recorded --browser-verification-required >/dev/null 2>&1; then echo 'COMPLETE accepted without browser verification' >&2; exit 1; fi
if "$v" --goal-status COMPLETE --terminal-final --outcome-satisfied --gates-pass-or-accepted --verification-recorded --visual-verification-required >/dev/null 2>&1; then echo 'COMPLETE accepted without visual verification' >&2; exit 1; fi
if "$v" --goal-status BLOCKED --terminal-final --external-blocker --no-meaningful-local-work --external-state-change-required --thread-control-channel-degraded >/dev/null 2>&1; then echo 'BLOCKED accepted for thread-local control degradation' >&2; exit 1; fi
if "$v" --goal-status BLOCKED --terminal-final --external-blocker --no-meaningful-local-work --external-state-change-required --browser-verification-required >/dev/null 2>&1; then echo 'BLOCKED accepted for browser verification without external Chrome evidence' >&2; exit 1; fi
if "$v" --goal-status ACTIVE --browser-verification-required --verified-browser-evidence-handoff >/dev/null 2>&1; then echo 'Stale handoff accepted' >&2; exit 1; fi
if "$v" --goal-status ACTIVE --user-restart-chrome-requested >/dev/null 2>&1; then echo 'Restart request accepted without external Chrome evidence' >&2; exit 1; fi
if "$v" --goal-status ACTIVE --thread-control-channel-degraded --user-facing-status 'Browser bridge failed three times.' >/dev/null 2>&1; then echo 'Retry-count status accepted' >&2; exit 1; fi
if "$v" --goal-status ACTIVE --thread-control-channel-degraded --user-facing-status 'Stopped visual verification.' >/dev/null 2>&1; then echo 'Stopped-verification status accepted' >&2; exit 1; fi
if "$v" --goal-status BLOCKED --terminal-final --external-blocker --no-meaningful-local-work --external-state-change-required --pending-screenshot-evidence >/dev/null 2>&1; then echo 'BLOCKED accepted for pending screenshot evidence' >&2; exit 1; fi
if "$v" --goal-status ACTIVE --implementation-complete >/dev/null 2>&1; then echo 'Implementation completion accepted without goal review transition' >&2; exit 1; fi
if "$v" --goal-status ACTIVE --terminal-final --user-before-finish-commitment-pending >/dev/null 2>&1; then echo 'Before-finish commitment accepted without clarification' >&2; exit 1; fi
if "$v" --goal-status ACTIVE --goal-update-received --goal-update-route FUTURE_STEP --goal-update-summary 'Queue update' --goal-update-impact-reason 'Later dependency' --goal-update-acceptance-criteria 'Queued work passes' --goal-update-plan-updated --current-step-preserved --future-step-queued >/dev/null 2>&1; then echo 'Future update accepted without order and dependencies' >&2; exit 1; fi
if "$v" --goal-status ACTIVE --progress-update --progress-percent 50 --progress-current-step-percent 35 --progress-phase implementation --progress-current-step 'Update contract' --progress-evidence 'Owner inspected' --progress-current-action 'Patch validator' --progress-next-gate 'Run tests' >/dev/null 2>&1; then echo 'Progress accepted without understanding' >&2; exit 1; fi
if "$v" --goal-status ACTIVE --progress-update --progress-percent 50 --progress-phase implementation --progress-understanding 'Add dual progress' --progress-current-step 'Update contract' --progress-evidence 'Owner inspected' --progress-current-action 'Patch validator' --progress-next-gate 'Run tests' >/dev/null 2>&1; then echo 'Progress accepted without current-step percentage' >&2; exit 1; fi
if "$v" --goal-status DONE --status-only >/dev/null 2>&1; then echo 'Unknown goal status accepted' >&2; exit 1; fi
if "$v" --goal-status ACTIVE --progress-update --progress-percent 50 --progress-current-step-percent 35 --progress-phase invented --progress-understanding 'Check phase' --progress-current-step 'Update contract' --progress-evidence 'Owner inspected' --progress-current-action 'Patch validator' --progress-next-gate 'Run tests' >/dev/null 2>&1; then echo 'Unknown progress phase accepted' >&2; exit 1; fi
if "$v" --goal-status ACTIVE --thread-control-channel-degraded --browser-failure-stage 'tab claim' --browser-failure-reason 'TOKEN exposed' --browser-failure-next 'repair' --user-facing-status 'Chrome recovery: stage=tab claim; reason=TOKEN exposed; next=repair. Implementation continues.' >/dev/null 2>&1; then echo 'Uppercase secret marker accepted' >&2; exit 1; fi
"$v" --goal-status ACTIVE >/dev/null
"$v" --goal-status ACTIVE --terminal-final --status-only >/dev/null
"$v" --goal-status ACTIVE --implementation-complete --goal-review-started --goal-review-checklist-created --task-regression-review-started >/dev/null
"$v" --goal-status ACTIVE --terminal-final --user-before-finish-commitment-pending --before-finish-clarification-asked >/dev/null
"$v" --goal-status ACTIVE --goal-update-received --goal-update-route CURRENT_STEP --goal-update-summary 'Merge update' --goal-update-impact-reason 'Matches current step' --goal-update-acceptance-criteria 'Merged behavior passes' --goal-update-plan-updated --current-step-preserved --current-step-update-integrated >/dev/null
"$v" --goal-status ACTIVE --goal-update-received --goal-update-route PRIOR_STEP_CORRECTION --goal-update-summary 'Repair prior step' --goal-update-impact-reason 'Prior output incomplete' --goal-update-acceptance-criteria 'Repair verified' --goal-update-plan-updated --resume-point-recorded --current-step-paused --prior-step-reopened --prior-step-update-verified --resume-point-restored >/dev/null
"$v" --goal-status ACTIVE --goal-update-received --goal-update-route FUTURE_STEP --goal-update-summary 'Queue update' --goal-update-impact-reason 'Later dependency' --goal-update-acceptance-criteria 'Queued work passes' --goal-update-plan-updated --current-step-preserved --future-step-queued --future-step-order 4 --future-step-dependencies 'after current validation' >/dev/null
"$v" --goal-status ACTIVE --goal-update-received --goal-update-route INVALIDATES_CURRENT_WORK --goal-update-summary 'Replan current work' --goal-update-impact-reason 'Current plan invalid' --goal-update-acceptance-criteria 'New plan passes' --goal-update-plan-updated --resume-point-recorded --current-step-paused --replan-completed >/dev/null
"$v" --goal-status ACTIVE --terminal-final --goal-update-received --goal-update-route CONFLICT_OR_AMBIGUOUS --goal-update-summary 'Resolve conflict' --goal-update-impact-reason 'Requirements conflict' --goal-update-acceptance-criteria 'User decision recorded' --goal-update-plan-updated --resume-point-recorded --current-step-preserved --goal-update-clarification-asked >/dev/null
"$v" --goal-status COMPLETE --terminal-final --outcome-satisfied --gates-pass-or-accepted --verification-recorded --completion-audit "$audit" >/dev/null
if "$v" --goal-status COMPLETE --terminal-final --outcome-satisfied --gates-pass-or-accepted --verification-recorded --completion-audit "$audit" --post-completion-question-asked >/dev/null 2>&1; then echo 'Post-completion question accepted' >&2; exit 1; fi
"$v" --goal-status COMPLETE --terminal-final --outcome-satisfied --gates-pass-or-accepted --verification-recorded --completion-audit "$audit" --browser-verification-required --browser-verification-passed --visual-verification-required --visual-verification-passed >/dev/null
"$v" --goal-status COMPLETE --terminal-final --outcome-satisfied --gates-pass-or-accepted --verification-recorded --completion-audit "$audit" --browser-verification-required --visual-verification-required --verified-browser-evidence-handoff --handoff-matches-current-code-state --thread-control-channel-degraded --browser-failure-stage 'tab claim' --browser-failure-reason 'ownership conflict recorded' --browser-failure-next 'use verified handoff' --user-facing-status 'Chrome recovery: stage=tab claim; reason=ownership conflict recorded; next=use verified handoff. Implementation continues.' >/dev/null
"$v" --goal-status ACTIVE --thread-control-channel-degraded --browser-failure-stage 'tab discovery' --browser-failure-reason 'Chrome extension returned no tabs' --browser-failure-next 'reconnect existing Chrome' --user-facing-status 'Chrome recovery: stage=tab discovery; reason=Chrome extension returned no tabs; next=reconnect existing Chrome. Implementation continues.' >/dev/null
"$v" --goal-status ACTIVE --pending-screenshot-evidence >/dev/null
"$v" --goal-status ACTIVE --progress-update --progress-percent 50 --progress-current-step-percent 35 --progress-phase implementation --progress-understanding 'Add dual progress' --progress-current-step 'Update contract' --progress-evidence 'Owner inspected' --progress-current-action 'Patch validator' --progress-next-gate 'Run tests' >/dev/null
"$v" --goal-status BLOCKED --terminal-final --external-blocker --no-meaningful-local-work --external-state-change-required >/dev/null
"$v" --goal-status BLOCKED --terminal-final --external-blocker --no-meaningful-local-work --external-state-change-required --browser-verification-required --chrome-externally-unavailable >/dev/null
echo 'Unix goal lifecycle tests passed'
